site_name: GenModes, a framework for generic modeling in energy systems
repo_url: https://github.com/AntaresSimulatorTeam/andromede-modeling-prototype
nav:
  - 'Home': 'index.md'
  - 'Getting started': 'getting-started.md'
  - 'User guide: GenModes language and dataformat': 
    - 'Mathematical expressions and syntax': 'user-guide/syntax.md'
    - 'Libraries': 'user-guide/libraries.md'
    - 'Models': 'user-guide/models.md'
    - 'Reference libraries' : 'user-guide/reference-libraries.md'
    - 'Systems': 'user-guide/systems.md'
    - 'Data series': 'user-guide/data.md'
  - 'User guide: Python interpreter package':
    - 'Reading input files': 'user-guide/inputs.md'
    - 'Building systems with the Python API': 'user-guide/building.md'
    - 'Optimization: building and solving problems': 'user-guide/optimization.md'
    - 'Retrieving outputs': 'user-guide/outputs.md'
    - 'Data converters': 'user-guide/converters.md'
  - Developer guide: developer-guide.md
  - Changelog: CHANGELOG.md

theme:
  name: material
  # logo: assets/logo.png #TODO: We need a logo !!
  # favicon: assets/Icone.png
  prev_next_buttons_location: none
  features:
    - navigation.instant
    - navigation.top
    - content.tabs.link
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: antares
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [ src ]
          options:
            show_bases: false
            show_source: false

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences