# Copyright (c) 2024, RTE (https://www.rte-france.com)
#
# See AUTHORS.txt
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#
# SPDX-License-Identifier: MPL-2.0
#
# This file is part of the Antares project.

from pathlib import Path

import numpy as np
import pytest

from gems.simulation.thermal_heuristic import find_nb_units_fast
from gems.study.data import ComponentParameterIndex
from gems.study.folder import load_study

DATA_DIR = Path(__file__).parent / "data/thermal_heuristic_six_clusters"
STUDY_DIR = Path(__file__).parent / "studies/thermal_heuristic_six_clusters"
CLUSTERS = ["G1", "G2", "G3", "G4", "G5", "G6"]


@pytest.fixture
def data_path() -> Path:
    return DATA_DIR


def test_accurate_heuristic() -> None:
    """
    Check that the accurate heuristic finds the same solution in the POC and in Antares with the same input generated by Antares.
    """

    # number_hours = 168
    # network = get_network(
    #     input_components,
    #     port_types=[],
    #     models=[AccurateModelBuilder(THERMAL_CLUSTER_MODEL_MILP).model],
    # )
    # database = get_database(
    #     input_components,
    #     data_path,
    #     fast=False,
    #     cluster=heuristic_components,
    #     time_scenario_hour_parameter=time_scenario_parameters,
    # )

    # thermal_problem_builder = ThermalProblemBuilder(
    #     network=network,
    #     database=database,
    #     time_scenario_hour_parameter=time_scenario_parameters,
    # )

    # for j, cluster in enumerate(heuristic_components):
    #     input_data = np.loadtxt(data_path / f"accurate/itr1_accurate_cluster{j+1}.txt")
    #     nb_on_1 = pd.DataFrame(
    #         np.transpose(np.ceil(np.round(input_data, 12))),
    #         index=list(range(number_hours)),
    #         columns=[week_scenario_index.scenario],
    #     )
    #     thermal_problem_builder.database.add_data(
    #         cluster, "nb_units_min", TimeScenarioSeriesData(nb_on_1)
    #     )

    #     # Solve heuristic problem
    #     resolution_step_accurate_heuristic = (
    #         thermal_problem_builder.heuristic_resolution_step(
    #             index=week_scenario_index,
    #             id_component=cluster,
    #             model=HeuristicAccurateModelBuilder(THERMAL_CLUSTER_MODEL_MILP).model,
    #         )
    #     )
    #     status = resolution_step_accurate_heuristic.solver.Solve(solver_parameters)
    #     assert status == pywraplp.Solver.OPTIMAL

    #     nb_on_heuristic = np.transpose(
    #         np.ceil(
    #             np.array(
    #                 OutputValues(resolution_step_accurate_heuristic)
    #                 .component(cluster)
    #                 .var("nb_on")
    #                 .value
    #             )
    #         )
    #     )

    #     expected_output = np.loadtxt(
    #         data_path / f"accurate/itr2_accurate_cluster{j+1}.txt"
    #     )
    #     assert list(nb_on_heuristic[:, 0]) == [
    #         pytest.approx(x) for x in expected_output
    #     ]
    pass


def test_fast_heuristic() -> None:
    """
    Check that find_nb_units_fast produces the same min_generating as Antares with
    the same LP production input.
    """
    number_hours = 168
    scenario = 0

    study = load_study(STUDY_DIR)

    for j, cluster in enumerate(CLUSTERS):
        p_max = float(study.database.get_value(ComponentParameterIndex(cluster, "max_power_per_unit"), 0, scenario))
        p_min = float(study.database.get_value(ComponentParameterIndex(cluster, "min_power_per_unit"), 0, scenario))
        d_min_up = int(study.database.get_value(ComponentParameterIndex(cluster, "min_up_duration"), 0, scenario))
        d_min_down = int(study.database.get_value(ComponentParameterIndex(cluster, "min_down_duration"), 0, scenario))

        generation_power = np.loadtxt(DATA_DIR / f"fast/itr1_fast_cluster{j+1}.txt").tolist()

        nb_units_on = find_nb_units_fast(
            generation_power=generation_power,
            min_power_per_unit=p_min,
            max_power_per_unit=p_max,
            min_up_duration=d_min_up,
            min_down_duration=d_min_down,
        )

        expected_output = np.loadtxt(DATA_DIR / f"fast/itr2_fast_cluster{j+1}.txt")
        for t in range(number_hours):
            max_generating = float(study.database.get_value(
                ComponentParameterIndex(cluster, "cluster_max_generation"), t, scenario
            ))
            min_generating = min(nb_units_on[t] * p_min, max_generating)
            assert min_generating == pytest.approx(expected_output[t])
