name: CI
on:
  push:
    branches:
      - "**"

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv pip install -e ".[dev]"

      - name: Check imports sort order
        uses: isort/isort-action@v1
        with:
          sort-paths: src, tests
          configuration: --profile black --check-only --diff

      - name: Check formatting
        uses: psf/black@stable
        with:
          version: "~=24.0"
          options: --check --diff

      - name: Check typing
        run: |
          python -m mypy

      - name: Test
        run: |
          pytest --cov gems --cov-report xml

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: python-code-coverage-report
          path: coverage.xml
